#ifndef BL_ERROR_H
#define BL_ERROR_H

typedef enum {
	BL_STATUS_SUCCESS = 0,
	BL_STATUS_FAILURE,

	// General errors.
	BL_STATUS_UNSUPPORTED,
	BL_STATUS_INVALID_PARAMETERS,
	BL_STATUS_INSUFFICIENT_RESOURCES,

	// Heap related error codes.
	BL_STATUS_MEMORY_ALLOCATION_FAILED,

	// Loading modules. 
	BL_STATUS_INVALID_MODULE_LIST,
	BL_STATUS_INVALID_MODULE,
	BL_STATUS_MODULE_ALREADY_LOADED,
	BL_STATUS_INVALID_ELF,
	BL_STATUS_INVALID_MODULE_SIZE,
	BL_STATUS_UNKNOWN_SYMBOL,

	// File system erros.
	BL_STATUS_INVALID_FILE_NAME,
	BL_STATUS_INVALID_FILE_TYPE,
	BL_STATUS_PATH_CONSTRUCTION_FAILED,
	BL_STATUS_INVALID_FILE_SYSTEM,
	BL_STATUS_FILE_NOT_FOUND,
	BL_STATUS_FILE_SYSTEM_ERROR,

	// Various disk errors.
	BL_STATUS_DISK_OPERATION_TIMEOUT,
	BL_STATUS_DISK_CONTROLLER_INTERNAL_ERROR,
	BL_STATUS_UNPROPER_DISK,
	BL_STATUS_UNBOOTABLE_DISK,
	BL_STATUS_INACTIVE_PARTITIONS,
	BL_STATUS_UNINITIALIZED_DISK,
	BL_STATUS_UNPROPER_CLUSTER_SIZE,
	BL_STATUS_UNPROPER_DISK_DATA,

	// USB errors.
	BL_STATUS_USB_INVALID_DEVICE,
	BL_STATUS_USB_INVALID_HOST_CONTROLLER,
	BL_STATUS_USB_INTERNAL_ERROR,
	BL_STATUS_USB_ACTION_NOT_FINISHED,
	BL_STATUS_USB_SHOULD_CHECK_STATUS,
	BL_STATUS_USB_CRC_ERROR,
	BL_STATUS_USB_BITSTUFF_ERROR,
        BL_STATUS_USB_TIMEOUT_ERROR,
        BL_STATUS_USB_NAK_RECEIVED,
        BL_STATUS_USB_BABBLE_DETECTED,
        BL_STATUS_USB_DATA_BUFFER_ERROR,
        BL_STATUS_USB_STALLED,

	// Graphics errors.
	BL_STATUS_GRAPHICS_NO_PROTOCOLS,
	BL_STATUS_GRAPHICS_PROTOCOL_UNSUPPORTED,

	// Iterator errors.
	BL_STATUS_ITERATOR_END,

} bl_status_t;

#endif

