#ifndef BL_DESCRIPTORS_H
#define BL_DESCRIPTORS_H

#define BL_GDT_CODE_SEGMENT_PROTECTED_MODE	0x08
#define BL_GDT_DATA_SEGMENT_PROTECTED_MODE	0x10
#define BL_GDT_CODE_SEGMENT_REAL_MODE		0x18
#define BL_GDT_DATA_SEGMENT_REAL_MODE		0x20

#endif

