#ifndef BL_PS2_KEYBOARD_H
#define BL_PS2_KEYBOARD_H

#include "include/io.h"

#define BL_PS2_KEYBOARD_NO_KEY	-1

/* PS/2 Keyboard data & status functions */
enum {
	BL_PS2_KEYBOARD_FUNCTION_DATA_INPUT_REGISTER	= 0x60, /* inb */
	BL_PS2_KEYBOARD_FUNCTION_DATA_OUTPUT_REGISTER	= 0x60, /* outb */
	BL_PS2_KEYBOARD_FUNCTION_STATUS_REGISTER	= 0x64, /* inb */
	BL_PS2_KEYBOARD_FUNCTION_SEND_COMMAND		= 0x64, /* outb */
};

/* The keyboard controller (such as 8042) status register
   which is located at I/O port (8-bit read-only) address 0x64. */
enum {
	BL_PS2_KEYBOARD_STATUS_REGISTER_OUTPUT_BUFFER_FULL	= 0x01,
	BL_PS2_KEYBOARD_STATUS_REGISTER_INPUT_BUFFER_FULL	= 0x02,
};

/* PS/2 Keyboard commands */
enum {
	BL_PS2_KEYBOARD_COMMAND_SET_RESET_LED		= 0xed,
	BL_PS2_KEYBOARD_COMMAND_GET_SET_SCAN_CODE	= 0xf0,
	BL_PS2_KEYBOARD_COMMAND_ENABLE_SCANNING	= 0xf4,
};

/* PS/2 Keyboard controller commands */
enum {
	BL_PS2_KEYBOARD_COMMAND_READ_CONFIG	= 0x20,
	BL_PS2_KEYBOARD_COMMAND_WRITE_CONFIG	= 0x60,
	BL_PS2_KEYBOARD_COMMAND_SELF_TEST		= 0xaa,
	BL_PS2_KEYBOARD_COMMAND_INTERFACE_TEST	= 0xab,
};

/* Success status for the 0xaa controller self test */
#define BL_PS2_KEYBOARD_SELF_TEST_OK	0x55

/* PS/2 Keyboard response */
enum {
	BL_PS2_KEYBOARD_REPONOSE_ECHO	= 0xee,
	BL_PS2_KEYBOARD_RESPONSE_ACK	= 0xfa,
	BL_PS2_KEYBOARD_RESPONSE_NACK	= 0xfe,
};

/* PS/2 Keyboard LED set/reset */
enum {
	BL_PS2_KEYBOARD_SET_LED_SCROLL_LOCK	= 0x01,
	BL_PS2_KEYBOARD_SET_LED_NUM_LOCK	= 0x02,
	BL_PS2_KEYBOARD_SET_LED_CAPS_LOCK	= 0x03,
};

/* PS/2 Keyboard scan code set information */
enum {
	BL_PS2_KEYBOARD_SCAN_CODE_GET_CURRENT	= 0x00,
	BL_PS2_KEYBOARD_SCAN_CODE_SET_1	= 0x01,
	BL_PS2_KEYBOARD_SCAN_CODE_SET_2	= 0x02,
	BL_PS2_KEYBOARD_SCAN_CODE_SET_3	= 0x03,
};

/* Unprintable characters - Scan code set 2 */
#define BL_PS2_KEYBOARD_UNPRINTABLE_KEY 0xff000000

enum {
	BL_KEY_F1 	=	(0x05 | BL_PS2_KEYBOARD_UNPRINTABLE_KEY),
	BL_KEY_F2 	=	(0x06 | BL_PS2_KEYBOARD_UNPRINTABLE_KEY),
	BL_KEY_F3 	=	(0x04 | BL_PS2_KEYBOARD_UNPRINTABLE_KEY),
	BL_KEY_F4 	=	(0x0c | BL_PS2_KEYBOARD_UNPRINTABLE_KEY),
	BL_KEY_F5 	=	(0x03 | BL_PS2_KEYBOARD_UNPRINTABLE_KEY),
	BL_KEY_F6 	=	(0x0b | BL_PS2_KEYBOARD_UNPRINTABLE_KEY),
	BL_KEY_F7 	=	(0x83 | BL_PS2_KEYBOARD_UNPRINTABLE_KEY),
	BL_KEY_F8 	=	(0x0a | BL_PS2_KEYBOARD_UNPRINTABLE_KEY),
	BL_KEY_F9 	=	(0x01 | BL_PS2_KEYBOARD_UNPRINTABLE_KEY),
	BL_KEY_F10	=	(0x09 | BL_PS2_KEYBOARD_UNPRINTABLE_KEY),
	BL_KEY_F11	=	(0x78 | BL_PS2_KEYBOARD_UNPRINTABLE_KEY),
	BL_KEY_F12	=	(0x07 | BL_PS2_KEYBOARD_UNPRINTABLE_KEY),
	BL_KEY_LSHIFT	=	(0x12 | BL_PS2_KEYBOARD_UNPRINTABLE_KEY),
	BL_KEY_RSHIFT	=	(0x59 | BL_PS2_KEYBOARD_UNPRINTABLE_KEY),
};

#endif

