# Objects.
CORE_OBJS += $(BL_SHELL)/shell.o $(BL_SHELL)/command.o
CORE_OBJS += $(BL_SHELL)/help.o
CORE_OBJS += $(BL_SHELL)/true.o $(BL_SHELL)/false.o
CORE_OBJS += $(BL_SHELL)/last-result.o
CORE_OBJS += $(BL_SHELL)/pci-list.o
CORE_OBJS += $(BL_SHELL)/usb-list.o
CORE_OBJS += $(BL_SHELL)/storage-list.o

